Add ikkeSendtSoknadVarsel til ny søknad
navikt/dinesykmeldte-backend pull request #54
Opened 2022-03-07 15:56 UTC by andreasDev

2022-03-07 17:22 UTC, tiafiring approved these changes

2022-03-08 08:38 UTC, karl-run approved these changes

2022-03-08 08:50 UTC, karl-run requested changes
sendt søknad kan ikke ha denne booleanenen

2022-03-08 08:57 UTC, karl-run approved these changes

2022-03-08 10:04 UTC, merged